AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal isolated spot instance configuration with Auto Scaling Group

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  # プライベートサブネット
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  # セキュリティグループ
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for isolated spot instances"
      VpcId: !Ref VPC
      # Egressルールなし = 完全隔離

  # 起動テンプレート（MixedInstancesPolicyでスポット設定するため、ここではスポット設定しない）
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        SecurityGroupIds:
          - !Ref SecurityGroup

  # 複数インスタンスタイプ対応のAuto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      CapacityRebalance: true
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt LaunchTemplate.LatestVersionNumber
          Overrides:
            # 同等の計算能力を持つインスタンスタイプ
            - InstanceType: t3.micro
              WeightedCapacity: 1
            - InstanceType: t3a.micro
              WeightedCapacity: 1
            - InstanceType: t4g.micro  # ARM版（AMIが対応している場合のみ）
              WeightedCapacity: 1
            - InstanceType: t2.micro
              WeightedCapacity: 1
        InstancesDistribution:
          OnDemandPercentageAboveBaseCapacity: 0  # 100%スポット
          SpotAllocationStrategy: price-capacity-optimized  # ベストプラクティス
