AWSTemplateFormatVersion: '2010-09-09'
Description:
  Create VPC & public/private subnet

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1aCidrBlock:
    Type: String
    Default: 10.0.0.0/24

  PublicSubnet1cCidrBlock:
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1aCidrBlock:
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1cCidrBlock:
    Type: String
    Default: 10.0.3.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-vpc

  RouteTableForPublicSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-rt-for-public-subnet

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-rt-for-private-subnet

  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1aCidrBlock
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-subnet-1a

  AssociateRouteTableForPublicSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref RouteTableForPublicSubnet

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1cCidrBlock
      AvailabilityZone: !Sub ${AWS::Region}c
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-subnet-1c

  AssociateRouteTableForPublicSubnet1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref RouteTableForPublicSubnet

  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1aCidrBlock
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-private-subnet-1a

  AssociateRouteTableForPrivateSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1cCidrBlock
      AvailabilityZone: !Sub ${AWS::Region}c
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-private-subnet-1c

  AssociateRouteTableForPrivateSubnet1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1c
      RouteTableId: !Ref PrivateRouteTable

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteForPublicSubnet:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"

  StackPublicSubnet1a:
    Description: The ID of the VPC Subnet
    Value: !Ref PublicSubnet1a
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1a"

  StackPublicSubnet1c:
    Description: The ID of the VPC Subnet
    Value: !Ref PublicSubnet1c
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1c"

  StackPrivateSubnet1a:
    Description: The ID of the VPC Subnet
    Value: !Ref PrivateSubnet1a
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1a"

  StackPrivateSubnet1c:
    Description: The ID of the VPC Subnet
    Value: !Ref PrivateSubnet1c
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1c"

