AWSTemplateFormatVersion: "2010-09-09"

Description: Create MySQL DataBase and DBSubnetGroup

Parameters:
  DatabaseMasterUsername:
    Type: String
    Default: admin
    Description: Database master username

  DatabasePassword:
    Type: String
    Description: Database password
    NoEcho: "true"

  DatabaseName:
    Type: String
    Default: MyDatabase
    Description: Database name

Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref AWS::StackName
      Engine: MySQL
      EngineVersion: 5.7
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 10
      StorageType: gp2
      MasterUsername: !Ref DatabaseMasterUsername
      MasterUserPassword: !Ref DatabasePassword
      DBName: !Ref DatabaseName
      VPCSecurityGroups:
        - !ImportValue MySecurityGroupForDB
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: "false"
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Database Subnet Group
      SubnetIds:
        - !ImportValue MyPrivateSubnet1a
        - !ImportValue MyPrivateSubnet1c
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet-group