AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7,
                  "tagStatus": "untagged"
                },
                "description": "Untagged images",
                "rulePriority": 1
              }
            ]
          }

Outputs:
  EcrRepository:
    Value: !Ref EcrRepository
    Export:
      Name: !Sub "${AWS::StackName}-common-EcrRepository"
