AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcStackName:
    Type: String
    Default: "common-vpc"

Resources:
  # インターネット公開のALB用セキュリティグループ
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for ALB"
      GroupName: !Sub "${AWS::StackName}-alb-sg"
      VpcId:
        Fn::ImportValue:
          !Sub "${VpcStackName}-VpcId"

  LoadBalancerSecurityGroupHttpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LoadBalancerSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0
      Description: Allow HTTP traffic

  LoadBalancerSecurityGroupHttpsIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LoadBalancerSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
      Description: Allow HTTPS traffic

  LoadBalancerSecurityGroupEgressAll:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref LoadBalancerSecurityGroup
      IpProtocol: "-1"
      CidrIp: 0.0.0.0/0
      Description: Allow all outbound traffic


  # コンテナアプリ用セキュリティグループ
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow Access From LoadBalancer to WebApp Service"
      GroupName: !Sub "${AWS::StackName}-webapp-sg"
      VpcId:
        Fn::ImportValue:
          !Sub "${VpcStackName}-VpcId"

  # Internet ALB -> WebApp Container
  WebAppSecurityGroupIngressFromLoadBalancer:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref WebAppSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      Description: Allow HTTP traffic from LoadBalancer to WebApp

  WebAppSecurityGroupEgressAllTraffic:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref WebAppSecurityGroup
      IpProtocol: "-1"
      CidrIp: 0.0.0.0/0
      Description: "Allow all outbound traffic by default"

Outputs:
    LoadBalancerSecurityGroup:
        Description: Common Security Group for ALB
        Value: !Ref LoadBalancerSecurityGroup
        Export:
          Name: !Sub "${AWS::StackName}-LoadBalancerSecurityGroup"
    WebAppSecurityGroup:
        Description: Common Security Group for WebApp Container
        Value: !Ref WebAppSecurityGroup
        Export:
          Name: !Sub "${AWS::StackName}-WebAppSecurityGroup"
