AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcStackName:
    Type: String
    Default: "common-vpc"

Resources:
  #======================
  # Security Group
  #======================
  # インターネット公開のセキュリティグループ： ALB
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for ALB"
      GroupName: !Sub "${AWS::StackName}-alb-sg"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: from 0.0.0.0/0:80
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      VpcId:
        Fn::ImportValue:
          !Sub "${VpcStackName}-VpcId"

  # コンテナアプリ用セキュリティグループ
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow Access From LoadBalancer to WebApp Service"
      GroupName: !Sub "${AWS::StackName}-bg-container-sg"
      VpcId:
        Fn::ImportValue:
          !Sub "${VpcStackName}-VpcId"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"

  # ルール紐付け
  ## Internet LB -> WebApp Container
  WebAppSgFromLoadBalancerSg:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: HTTP for Ingress
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      GroupId: !Ref WebAppSecurityGroup
      SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

Outputs:
    LoadBalancerSecurityGroup:
        Description: Common Security Group for ALB
        Value: !Ref LoadBalancerSecurityGroup
        Export:
          Name: !Sub "${AWS::StackName}-LoadBalancerSecurityGroup"
    WebAppSecurityGroup:
        Description: Common Security Group for WebApp Container
        Value: !Ref WebAppSecurityGroup
        Export:
          Name: !Sub "${AWS::StackName}-WebAppSecurityGroup"
