apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-external-secret
spec:
  data:
    - secretKey: client_id
      remoteRef:
        key: argocd-github-oidc-stg
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: argocd-github-oidc-stg
        property: client_secret
