apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repository-external-secret
spec:
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-github-private-key-stg
