configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
    url: https://argocd.stg.ngsw-app.click
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-oidc-secret:client_id
            clientSecret: $argocd-oidc-secret:client_secret

  params:
    server.insecure: true
  rbac:
    policy.csv: |
      g, otsda1055@yahoo.co.jp, role:admin
    policy.default: role:readonly
    scopes: '[email]'
