AWSTemplateFormatVersion: "2010-09-09"

Description: Create EC2 Instance for WebServer

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type

  ImageId:
    Description: Id of AMI
    Type: String
    Default: ami-0218d08a1f9dac831 # Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type (64bit x86) / ap-northeast-1
    ConstraintDescription: must be a valid image id

  KeyName:
    Description : Name of an existing EC2 KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription : Can contain only ASCII characters.

  InstallNginx:
    Description: Do you want to install Nginx?
    Type: String
    Default: "Yes"
    AllowedValues:
    - "Yes"
    - "No"

Conditions:
  InstallNginx: !Equals [ !Ref InstallNginx, "Yes" ]

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 8
      NetworkInterfaces:
        - SubnetId: !ImportValue MyPublicSubnet1a
          GroupSet:
            - !ImportValue MySecurityGroupForWebServer
          AssociatePublicIpAddress: true
          DeviceIndex : 0
      KeyName: !Ref KeyName
      UserData: !If
        - InstallNginxgs
        # InstallNginx == true の場合
        - !Base64 |
          #!/bin/bash
          echo -e "===== yum update -y =====\n"
          yum update -y

          echo -e "===== amazon-linux-extras install nginx1.12 -y =====\n"
          amazon-linux-extras install nginx1.12 -y

          # nginxの初期設定ファイルをバックアップ
          echo -e "===== cp -a /etc/nginx/nginx.conf /etc/nginx/nginx.conf.back =====\n"
          cp -a /etc/nginx/nginx.conf /etc/nginx/nginx.conf.back

          echo -e "===== systemctl start nginx =====\n"
          systemctl start nginx

          echo -e "===== systemctl enable nginx =====\n"
          systemctl systemctl enable nginx
        # InstallNginx == false の場合
        - !Ref AWS::NoValue
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName