apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:ngsw877/aws-infrastructure.git
    path: kubernetes/eks/alb-controller/overlays/stg
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
