apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-transfer
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:cloud-pratica/cloud-pratica-backend
    path: ops/kubernetes/eks/log-transfer/overlays/stg
    targetRevision: develop
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
