apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: cp-k8s-stg
    # *.stg.sample-app.click のhttps証明書
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:374146079343:certificate/660c426f-0c58-4745-8e4d-79c491c45b73
spec:
  rules:
    - host: sm-api-v2.stg.ngsw-app.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slack-metrics-service
                port:
                  number: 80