AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RepositoryName:
    Type: String
    Default: "sample-app"

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      RepositoryName: !Ref RepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7,
                  "tagStatus": "untagged"
                },
                "description": "Untagged images",
                "rulePriority": 1
              }
            ]
          }

Outputs:
  EcrRepositoryName:
    Value: !Ref EcrRepository
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepositoryName"
  EcrRepositoryArn:
    Value: !GetAtt EcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepositoryArn"
