AWSTemplateFormatVersion: '2010-09-09'
Description: IPアドレス制限付きの、静的Webサイトホスティング用S3バケットを作成する

Parameters:
  BucketName:
    Type: String
    Default: web-site-hosting-bucket
  AllowedIpAddress:
    Type: String

Resources:
  WebSiteHostingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebSiteHostingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadGetObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebSiteHostingBucket}/*'
            Condition:
              IpAddress:
                aws:SourceIp:
                  - !Ref AllowedIpAddress
