AWSTemplateFormatVersion: '2010-09-09'
Description: IPアドレス制限付きの、静的Webサイトホスティング用S3バケットを作成する

Parameters:
  BucketName:
    Type: String
    Default: "web-site-hosting-bucket-with-ip-limit"
  AllowedIpAddress:
    Type: String
    Default: "x.x.x.x"

Resources:
  WebSiteHostingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: index.html
      # アクセスを許可するIPアドレスが指定されているとバケットポリシーでのIPアドレス制限がされるため、
      # 「パブリックアクセスをすべてブロック：オン」に設定する
      # 参考：https://techblog.ap-com.co.jp/entry/2024/01/26/215603
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebSiteHostingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadGetObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebSiteHostingBucket}/*'
            Condition:
              IpAddress:
                aws:SourceIp:
                  - !Ref AllowedIpAddress
