AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Apigw + Lambda + DynamoDB

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:  
  Runtime:
    Type: String
    Default: "python3.9"
    Description: "Lambda関数のランタイムを指定します"

  TableName:
    Type: String
    Default: "SampleTable"
    Description: "DynamoDBテーブルの名前を指定します"
  
Resources:
  MyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: !Ref Runtime
      Architectures:
        - x86_64
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref TableName
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Path: /insert
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName

  MyDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref TableName

Outputs:
  Api:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/insert/"
