AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Fqdn:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Fqdn
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref Fqdn
          # Route53をドメインレジストラーとして使用している場合に利用可能で、ACMによってCNAMEがドメインレコードに追加されます
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn"
  Fqdn:
    Value: !Ref Fqdn
    Export:
      Name: !Sub "${AWS::StackName}-Fqdn"
  HostedZoneId:
    Value: !Ref HostedZoneId
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneId"
