name: "Build and Push Image"
description: "Composite action for building and pushing Docker images."

inputs:
  aws-region:
    description: "AWS region."
    required: true
  role-to-assume:
    description: "The AWS role to assume."
    required: true
  context:
    description: "The Docker build context path."
    required: true
  ecr-image-tag:
    description: "The combined ECR image URI and tag in the format 'repository:tag'."
    required: true
  cache-scope:
    description: "Cache scope for docker build (e.g. 'app' or 'web')."
    required: true
  build-args:
    description: "Additional build arguments (optional)."
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: 'true'
        mask-aws-account-id: 'true'
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        push: 'true'
        provenance: 'false'
        tags: ${{ inputs.ecr-image-tag }}
        cache-from: type=gha,scope=${{ inputs.cache-scope }}
        cache-to: type=gha,scope=${{ inputs.cache-scope }},mode=max
        build-args: ${{ inputs.build-args }}