apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repository-external-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cp-css
    kind: ClusterSecretStore
  target:
    # 既存のsecretにマージする
    name: argocd-repository-secret
    creationPolicy: Merge
