apiVersion: v1
kind: Secret
metadata:
  name: argocd-repository-secret
  namespace: argocd
  labels:
    # Argo CDは指定のラベルをつけたSecretを作成することで、自動的に連携設定を読み込んでくれる。
    # 参考: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: default
  name: cp-backend
  url: git@github.com:ngsw877/aws-infrastructure.git
  # sshPrivateKeyはexternal-secretからマージされる
