name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs (multi workflows)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          GITHUB_REPO="${{ github.repository }}"
          
          # GitHub Actionsの実行履歴を削除したいworkflowファイルを指定
          WORKFLOW_FILES=(
            "./ecs-auto-deploy.yml"
            "./ecs-manual-deploy.yml"
            "./s3-auto-deploy.yml"
            "./s3-manual-deploy.yml"
            "./cleanup-workflow-runs.yml"
          )

          # 指定したworkflowファイルごとに実行履歴を全て削除
          for workflow_file in "${WORKFLOW_FILES[@]}"; do
            echo "Deleting old runs for ${workflow_file}..."
            gh api \
              -H "Authorization: token $GITHUB_TOKEN" \
              "repos/${GITHUB_REPO}/actions/workflows/${workflow_file}/runs?per_page=100" \
            | jq -r '.workflow_runs[].id' \
            | xargs -P4 -I{} gh api \
                -H "Authorization: token $GITHUB_TOKEN" \
                "repos/${GITHUB_REPO}/actions/runs/{}" \
                -X DELETE
          done