name: Deploy to Amazon ECS

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  CFN_STACK_NAME: ${{ secrets.CFN_STACK_NAME }}
  ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}

permissions:
  contents: read

jobs:
  build-and-push-app-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          mask-aws-account-id: false

      - uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build app image
        uses: docker/build-push-action@v4
        with:
          context: ./ecs/docker/php
          push: true
          provenance: false
          tags: ${{ env.ECR_REPO_URI }}:${{github.run_number}}-app
          cache-from: type=gha,scope=app
          cache-to: type=gha,mode=max,scope=app

  build-and-push-web-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          mask-aws-account-id: false

      - uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build web image
        uses: docker/build-push-action@v4
        env:
          BACKEND_APP_DOMAIN: "127.0.0.1"
          RESOLVER: "169.254.169.253"
        with:
          context: ./ecs/docker/nginx
          push: true
          provenance: false
          tags: ${{ env.ECR_REPO_URI }}:${{github.run_number}}-web
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web
          build-args: |
            BACKEND_APP_DOMAIN
            RESOLVER
           
