name: ECS Auto Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-ecs.yml
    secrets: inherit