name: ECS Auto Deploy
run-name: ECS Auto Deploy to 【${{ github.ref_name }}】

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - staging
      - develop
    paths:
      - demo-application/backend/**

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-ecs.yml