name: ECS Manual Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        description: デプロイ先環境名
        type: environment
        default: development
      branch:
        description: デプロイブランチ名
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-ecs.yml
    secrets: inherit
    with:
      deploy-to: ${{ inputs.deploy-to }}
      branch: ${{ inputs.branch }}