name: ECS Manual Deploy
run-name: ECS：${{ inputs.branch }} ブランチ ▶ ${{ inputs.deploy-to }} 環境【手動】

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        description: デプロイ先環境名
        type: environment
        default: development
      branch:
        description: デプロイブランチ名
        type: string
        required: true
      migration-mode:
        description: マイグレーション実行モード
        type: choice
        default: 'skip'
        options:
          - 'run'    # マイグレーションを実行
          - 'skip'   # マイグレーションを実行しない
      seeder-command:
        description: 'マイグレーション成功時に続けて実行するシーダーコマンド（例: php artisan db:seed --class=UserSeeder --force）'
        type: string
        required: false
        default: ':'

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-ecs.yml
    with:
      deploy-to: ${{ inputs.deploy-to }}
      branch: ${{ inputs.branch }}
      migration-mode: ${{ inputs.migration-mode }}
      seeder-command: ${{ inputs.seeder-command }}
