name: ECS Auto Deploy
run-name: ECS：${{ github.ref_name }} ブランチ ▶ ${{ github.ref_name }} 環境【自動】

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - staging
      - develop
    paths:
      - demo-application/backend/**

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-ecs.yml
