name: S3 Auto Deploy
run-name: S3：${{ github.ref_name }} ブランチ ▶ ${{ github.ref_name }} 環境【自動】

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - staging
      - develop
    paths:
      - demo-application/frontend/**

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/_deploy-to-s3.yml
